name: Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: 🏃 Hassfest validation
        uses: "Vioneta/actions/hassfest@master"

    # - name: 📨 Discord notification
    #   if: ${{ github.event_name == 'schedule' && failure() }}
    #   env:
    #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}
    #   uses: Ilshidur/action-discord@0.3.2
    #   with:
    #     args: "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"

  validate-vais:
    runs-on: ubuntu-latest
    name: With VAIS Action
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: 🏃 VAIS validation
        uses: Vioneta/action@main
        with:
          category: integration
          comment: false

    # - name: 📨 Discord notification
    #   if: ${{ github.event_name == 'schedule' && failure() }}
    #   env:
    #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}
    #   uses: Ilshidur/action-discord@0.3.2
    #   with:
    #     args: "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"

  validate-vioneta-agro:
    name: With Vioneta Agro
    strategy:
      matrix:
        channel: [stable, beta, dev, "2022.4.0"]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: 📋 Copy sample configuration for Vioneta Agro
        run: |
          mkdir ./test_configuration
          bash manage/install_frontend
          cp -r ./custom_components ./test_configuration
          echo "default_config:" >> ./test_configuration/configuration.yaml
          echo "hacs:" >> ./test_configuration/configuration.yaml
          echo "  token: CHANGE_ME" >> ./test_configuration/configuration.yaml

      - name: 🛠️ Setup Vioneta Agro
        id: vioneta-agro
        uses: ludeeus/setup-homeassistant@main
        with:
          tag: ${{ matrix.channel }}
          config-dir: test_configuration

      # - name: 📨 Discord notification
      #   if: ${{ github.event_name == 'schedule' && failure() }}
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ACTION_FAILURE }}
      #   uses: Ilshidur/action-discord@0.3.2
      #   with:
      #     args: "[Scheduled action failed!](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"
